Account for dots in view names
Our product Pipeline creates view names that sometimes have dots in them depending on how data is passed to our API. Redshift allows this, but this query breaks with the error below if `.` is not taken into account. 

```
ERROR:  cross-database references are not implemented: "schemaname.view.name"
Query failed
PostgreSQL said: cross-database references are not implemented: "schemaname.view.name"
```